export const AGENDAMENTO_CONFIG = {
  HORARIO_ABERTURA_PADRAO: '08:00',
  HORARIO_FECHAMENTO_PADRAO: '18:00',
  CAPACIDADE_PADRAO: 3,
  ANTECEDENCIA_MINIMA_PADRAO: 2,
  ANTECEDENCIA_MAXIMA_PADRAO: 60,
  PRAZO_CANCELAMENTO_PADRAO: 24,
  DIAS_CALENDARIO_PENDENTE_ALERTA: 25,
  ITENS_POR_PAGINA: 20,
  DEBOUNCE_BUSCA_MS: 300,
} as const;
