export const DB_CONFIG = {
  name: 'labmecsolos',
  version: 1,
  tables: [
    'pre_cadastro',
    'usuarios',
    'sessoes',
    'logs_sistema',
    'codigos_verificacao',
    'categorias_item',
    'itens',
    'materiais',
    'utensilios',
    'equipamentos',
    'lotes_material',
    'movimentacoes_estoque',
    'historico_estado_equipamento',
    'registros_equipamento',
    'ocorrencias',
    'pesquisas',
    'pesquisa_colaboradores',
    'programas_amostragem',
    'pontos_coleta',
    'amostras_brutas',
    'amostras_preparadas',
    'amostras_ensaiadas',
    'amostras_indeformadas',
    'ensaios',
    'ensaios_teor_umidade',
    'determinacoes_teor_umidade',
    'imagens',
    'agendamento_itens',
    'configuracoes_sistema',
    'metadados_amostra',
    'calendario_mensal',
    'calendario_dias',
    'agendamentos',
    'agendamento_datas',
    'agendamento_ensaios',
    'agendamento_itens',
  ],
} as const;
