export const ENSAIOS_CONFIG = {
  TEOR_UMIDADE: {
    TEMPERATURA_ESTUFA_MIN: 105,
    TEMPERATURA_ESTUFA_MAX: 110,
    DETERMINACOES_MINIMAS: 3,
    TEMPO_ESTUFA_RECOMENDADO_HORAS: 24,
    UNIDADE_MASSA: 'g',
    UNIDADE_TEMPERATURA: '°C',
    UNIDADE_TEMPO: 'h',
    UNIDADE_UMIDADE: '%'
  },

  ITENS_POR_PAGINA: 20,

  GPS_PRECISAO_MINIMA: 10,

  MAX_IMAGENS_POR_ENTIDADE: 20,

  RELATORIO_FORMATO: 'PDF'
} as const;
