export const INVENTARIO_CONFIG = {
  ITENS_POR_PAGINA: 20,
  DEBOUNCE_BUSCA_MS: 300,

  INTERVALOS_VALIDADE_PROXIMA: [30, 15, 7, 3, 1] as number[],
  INTERVALOS_CALIBRACAO_PROXIMA: [30, 15, 7, 3, 1] as number[],

  INTERVALO_VERIFICACAO_CALIBRACAO_HORAS: 24,

  QR_CODE_SIZE: 300,
  QR_CODE_FORMAT: 'PNG',

  MAX_FOTOS_OCORRENCIA: 5,

  RELATORIO_FORMATO: 'PDF',
} as const;
