export const SECURITY_CONFIG = {
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_REQUIRE_UPPERCASE: true,
  PASSWORD_REQUIRE_LOWERCASE: true,
  PASSWORD_REQUIRE_NUMBER: true,
  BCRYPT_SALT_ROUNDS: 10,

  SESSION_DURATION_DAYS: 30,

  VERIFICATION_CODE_LENGTH: 6,
  VERIFICATION_CODE_EXPIRY_MINUTES: 15,
  MAX_CODE_RESENDS: 3,

  MAX_LOGIN_ATTEMPTS: 5,
  LOGIN_BLOCK_DURATION_MINUTES: 15,

  ALLOWED_EMAIL_DOMAINS: ['@ufrn.br', '@ufrn.edu.br'],

  LOG_RETENTION_YEARS: 1,
} as const;
